---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api
  namespace: monitoring
  labels:
    collector: alloy
spec:
  namespaceSelector:
    matchNames: [backend-api]
  selector:
    matchLabels:
      app: backend-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
